### ISSUE TITLE
Failed to discover OP endpoint URL (message: No providers found for the given identifier)

### ISSUE THREAD

**Issue by hfcorriez** [jaredhanson/passport-google#3]
My first try of this library is succeed, But always error after that.

Any suggestion?

thx

```
Express
500 Failed to discover OP endpoint URL (message: No providers found for the given identifier)

    at Strategy.authenticate (/Users/hfcorriez/Code/dashboard/node_modules/passport-google/node_modules/passport-openid/lib/passport-openid/strategy.js:193:52)
    at openid.authenticate (/Users/hfcorriez/Code/dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:793:14)
    at openid.discover.i (/Users/hfcorriez/Code/dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:587:13)
    at _resolveHostMeta (/Users/hfcorriez/Code/dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:553:11)
    at _get.get.done (/Users/hfcorriez/Code/dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:201:9)
    at IncomingMessage._get (/Users/hfcorriez/Code/dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:205:32)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1366:20)
```

**Comment by Swapnilniwane91** [comment]
i receive this error while using passport google
InternalOpenIDError: Failed to discover OP endpoint URL
    at /home/esense-64/Desktop/swapnil_niwane/examples github/passport-google-master/examples/signon/node_modules/passport-google/node_modules/passport-openid/lib/passport-openid/strategy.js:249:52
    at /home/esense-64/Desktop/swapnil_niwane/examples github/passport-google-master/examples/signon/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:874:14
    at /home/esense-64/Desktop/swapnil_niwane/examples github/passport-google-master/examples/signon/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:664:13
    at /home/esense-64/Desktop/swapnil_niwane/examples github/passport-google-master/examples/signon/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:620:11
    at done (/home/esense-64/Desktop/swapnil_niwane/examples github/passport-google-master/examples/signon/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:258:9)
    at IncomingMessage.<anonymous> (/home/esense-64/Desktop/swapnil_niwane/examples github/passport-google-master/examples/signon/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:262:32)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by manikandants** [comment]
Getting the following error message when using passport-google@0.3.0
```
InternalOpenIDError: Failed to discover OP endpoint URL
   at /home/xenon/projects/cartisan-dashboard/node_modules/passport-google/node_modules/passport-openid/lib/passport-openid/strategy.js:249:52
   at /home/xenon/projects/cartisan-dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:874:14
   at /home/xenon/projects/cartisan-dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:664:13
   at /home/xenon/projects/cartisan-dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:620:11
   at done (/home/xenon/projects/cartisan-dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:258:9)
   at IncomingMessage.<anonymous> (/home/xenon/projects/cartisan-dashboard/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:262:32)
   at IncomingMessage.emit (events.js:129:20)
   at _stream_readable.js:908:16
   at process._tickCallback (node.js:355:11)
```

**Comment by ilkkao** [comment]
Google has discontinued openid support. This module simply doesn't work anymore.

**Comment by manikandants** [comment]
Thanks @ilkkao :+1: Figured out that we have to use [passport-google-oauth](https://github.com/jaredhanson/passport-google-oauth)
