### ISSUE TITLE
Does not work with cluster

### ISSUE THREAD

**Issue by buunguyen** [jaredhanson/passport-google#8]
I use passport-google. It works fine if only one node process is used.  As soon as the [cluster module](http://nodejs.org/api/cluster.html) is used with 2 or more worker processes, sometimes I receive the following error upon authentication:

```
Failed to verify assertion (message: Invalid association handle)
   at Strategy.authenticate.identifier (/app/node_modules/passport-google/node_modules/passport-openid/lib/passport-openid/strategy.js:143:36)
   at _verifyAssertionData (/app/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:992:12)
   at _verifyAssertionAgainstProvider (/app/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1123:14)
   at _checkSignatureUsingAssociation (/app/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1170:14)
   at Object.openid.loadAssociation (/app/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:111:5)
   at _checkSignatureUsingAssociation (/app/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1162:10)
   at _checkSignature (/app/node_modules/passport-google/node_modules/passport- openid/node_modules/openid/openid.js:1156:5)
   at _verifyAssertionAgainstProvider (/app/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1119:3)
   at _verifyDiscoveredInformation (/app/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:1084:16)
   at openid.discover (/app/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:607:7)
```

I have tried different session store, including cookie and redis, but the problem persists.  Does anyone succeed in using passport-google in a setup involving multiple node processes?

**Comment by jackrobertscott** [comment]
Passport.js does not work with clusters because it stores the session in the server (bad and not scalable). You don't want to store any session data in the server (keeping it stateless) as then you may scale up your clusters and handle more requests.

Here is a [tutorial I wrote on connecting to Google in a much better way](https://medium.com/@jackscott/how-to-use-google-auth-api-with-node-js-888304f7e3a0).
